#!/bin/bash

do_a_search() {

for i in `ls cookies`; 
do echo $i; 
curl -b cookies/$i --silent "http://www.carolinapicknpull.com/inventory/?make=${2}&model=${1}&inventory-search=Search" > /tmp/cfpnp_list.html && cat /tmp/cfpnp_list.html | grep -i $1 | grep -v \<option | cat /tmp/cfpnp_list.html | grep -i $1 | grep -v \<option | html2text | tr -d '|' | $3;
done

}

echo -e "Searching Cape Fear Pick-N-Pull Yards for Eclipse Types..."
do_a_search "eclipse" "mitsubishi" "egrep 19[90..99]"
echo -e "Searching Cape Fear Pick-N-Pull Yards for Talon Types..."
do_a_search "talon" "eagle" "egrep 19[90..99]"
echo -e "Searching Cape Fear Pick-N-Pull Yards for Focus Friends..."
do_a_search "focus" "ford" "egrep 20[08..11]"
echo -e "Searching Cape Fear Pick-N-Pull Yards for Mighty Max's..."
do_a_search "mighty+max" "mitsubishi" "egrep 19[90..99]"
echo -e "Searching Cape Fear Pick-N-Pull Yards for FD's..."
do_a_search "mazda-rx7" "mazda" "grep 94"
echo -e "Searching Cape Fear Pick-N-Pull Yards for rogue Rogues..."
do_a_search "rogue" "nissan" "egrep 20[08..12]"

#for i in `ls cookies`; do echo $i; curl -b cookies/$i --silent "http://www.carolinapicknpull.com/inventory/?make=ford&model=focus&inventory-search=Search" > /tmp/cfpnp_list.html && cat /tmp/cfpnp_list.html | grep -i focus | grep -v \<option | cat /tmp/cfpnp_list.html | grep -i focus | grep -v \<option | html2text | grep -e20{08..11} | tr -d '|'; done

echo -e "Search Complete!"
