#!/bin/bash

echo -e "Searching Cape Fear Pick-N-Pull Yards for Eclipse Types..."

for i in `ls cookies`; do echo $i; curl -b cookies/$i --silent "http://www.carolinapicknpull.com/inventory/?make=mitsubishi&model=eclipse&inventory-search=Search" > /tmp/cfpnp_list.html && cat /tmp/cfpnp_list.html | grep -i eclipse | grep -v \<option | cat /tmp/cfpnp_list.html | grep -i eclipse | grep -v \<option | html2text | egrep "19[90-99]" | tr -d '|'; done

echo -e "Searching Cape Fear Pick-N-Pull Yards for Talon Types..."
for i in `ls cookies`; do echo $i; curl -b cookies/$i --silent "http://www.carolinapicknpull.com/inventory/?make=eagle&model=talon&inventory-search=Search" > /tmp/cfpnp_list.html && cat /tmp/cfpnp_list.html | grep -i talon | grep -v \<option | cat /tmp/cfpnp_list.html | grep -i talon | grep -v \<option | html2text | egrep "19[90-99]" | tr -d '|'; done

echo -e "Searching Cape Fear Pick-N-Pull Yards for Focus Friends..."
for i in `ls cookies`; do echo $i; curl -b cookies/$i --silent "http://www.carolinapicknpull.com/inventory/?make=ford&model=focus&inventory-search=Search" > /tmp/cfpnp_list.html && cat /tmp/cfpnp_list.html | grep -i focus | grep -v \<option | cat /tmp/cfpnp_list.html | grep -i focus | grep -v \<option | html2text | grep -e20{08..11} | tr -d '|'; done

echo -e "Searching Cape Fear Pick-N-Pull Yards for RX-7's..."
for i in `ls cookies`; do echo $i; curl -b cookies/$i --silent "http://www.carolinapicknpull.com/inventory/?make=mitsubishi&model=mighty+max&inventory-search=Search" > /tmp/cfpnp_list.html && cat /tmp/cfpnp_list.html | grep -i max | grep -v \<option | cat /tmp/cfpnp_list.html | grep -i max | grep -v \<option | html2text | egrep "19[90-99]" | tr -d '|'; done

echo -e "Searching Cape Fear Pick-N-Pull Yards for Mighty Max Trucks..."
for i in `ls cookies`; do echo $i; curl -b cookies/$i --silent "http://www.carolinapicknpull.com/inventory/?make=mazda&model=mazda+rx7&inventory-search=Search" > /tmp/cfpnp_list.html && cat /tmp/cfpnp_list.html | grep -i rx7 | grep -v \<option | cat /tmp/cfpnp_list.html | grep -i rx7 | grep -v \<option | html2text | egrep "19[90-99]" | tr -d '|'; done

echo -e "Search Complete!"
